# Auto-generated by Setup.py.
import os
import runpy
import sys
from pathlib import Path

ROOT = Path('D:\\CatiaMCP\\Catia-MCP')
os.chdir(ROOT)
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
runpy.run_module("catia_mcp", run_name="__main__")
